#ifndef _COMMUNICATION_CONFIG_
#define _COMMUNICATION_CONFIG_


typedef enum{
    TAG_OK = 0,
    TAG_ERROR = -1,
    TAG_ADC_PICO,
    TAG_ADC_ADS1115_CH_1,
    TAG_ADC_ADS1115_CH_2,
    TAG_DIGITAL_SCOPE
}send_dataTag_t;


typedef enum{
    ADC_ADS1115_CH1_ENABLE,
    ADC_ADS1115_CH2_ENABLE,
    ADC_PICO_CH1_ENABLE,
    ADC_PICO_CH2_ENABLE,

    DIGITAL_PROBE_ENABLE,
    DIGITAL_MODE_FREERUN,
    DIGITAL_MODE_TRIGGERED,
    DIGITAL_SET_SAMPLE_FREQ,
    DIGITAL_SET_TIMER,

    DEVICE_STOP,
    DEVICE_RUN
}config_tag_t;


#endif